// automatically generated by the FlatBuffers compiler, do not modify

/* eslint-disable @typescript-eslint/no-unused-vars, @typescript-eslint/no-explicit-any, @typescript-eslint/no-non-null-assertion */

import * as flatbuffers from 'flatbuffers';

export class StoryContentItem {
  bb: flatbuffers.ByteBuffer|null = null;
  bb_pos = 0;
  __init(i:number, bb:flatbuffers.ByteBuffer):StoryContentItem {
  this.bb_pos = i;
  this.bb = bb;
  return this;
}

static getRootAsStoryContentItem(bb:flatbuffers.ByteBuffer, obj?:StoryContentItem):StoryContentItem {
  return (obj || new StoryContentItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

static getSizePrefixedRootAsStoryContentItem(bb:flatbuffers.ByteBuffer, obj?:StoryContentItem):StoryContentItem {
  bb.setPosition(bb.position() + flatbuffers.SIZE_PREFIX_LENGTH);
  return (obj || new StoryContentItem()).__init(bb.readInt32(bb.position()) + bb.position(), bb);
}

title():string|null
title(optionalEncoding:flatbuffers.Encoding):string|Uint8Array|null
title(optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 4);
  return offset ? this.bb!.__string(this.bb_pos + offset, optionalEncoding) : null;
}

content(index: number):string
content(index: number,optionalEncoding:flatbuffers.Encoding):string|Uint8Array
content(index: number,optionalEncoding?:any):string|Uint8Array|null {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__string(this.bb!.__vector(this.bb_pos + offset) + index * 4, optionalEncoding) : null;
}

contentLength():number {
  const offset = this.bb!.__offset(this.bb_pos, 6);
  return offset ? this.bb!.__vector_len(this.bb_pos + offset) : 0;
}

static startStoryContentItem(builder:flatbuffers.Builder) {
  builder.startObject(2);
}

static addTitle(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset) {
  builder.addFieldOffset(0, titleOffset, 0);
}

static addContent(builder:flatbuffers.Builder, contentOffset:flatbuffers.Offset) {
  builder.addFieldOffset(1, contentOffset, 0);
}

static createContentVector(builder:flatbuffers.Builder, data:flatbuffers.Offset[]):flatbuffers.Offset {
  builder.startVector(4, data.length, 4);
  for (let i = data.length - 1; i >= 0; i--) {
    builder.addOffset(data[i]!);
  }
  return builder.endVector();
}

static startContentVector(builder:flatbuffers.Builder, numElems:number) {
  builder.startVector(4, numElems, 4);
}

static endStoryContentItem(builder:flatbuffers.Builder):flatbuffers.Offset {
  return builder.endObject();
}

static createStoryContentItem(builder:flatbuffers.Builder, titleOffset:flatbuffers.Offset, contentOffset:flatbuffers.Offset):flatbuffers.Offset {
  StoryContentItem.startStoryContentItem(builder);
  StoryContentItem.addTitle(builder, titleOffset);
  StoryContentItem.addContent(builder, contentOffset);
  return StoryContentItem.endStoryContentItem(builder);
}
}
